### ISSUE TITLE
پیشنهاد توسعه

### ISSUE THREAD

**Issue by mehrdadashtari** [mfathi91/persian-date-time#5]
<div dir="rtl" lang="fa">سلام پیشنهادی دارم برای افزودن قابلیت نمایش رویداد به برنامه ای که توسعه دادید

الان که همه ی سیستم ها به اینترنت متصل هستند پیشنهاد میکنم ارتباط با ای پی آي های تقویم رو هم در این سورس خوب پیاده سازی کنید
خودم از این سرویس زیاد استفاده میکنم </div>
<a href="https://apieco.ir/api/farsicalendar">وب سرویس تقویم فارسی</a>

<div dir="rtl" lang="fa">اطلاعات خوبی ارائه میده مثل وقایع و مناسبت های هر روز و دریافت رویداد در حالت شمسی و قمری و میلادی</div>

**Comment by mfathi91** [comment]
سلام. ممنون بابت پیشنهادتون. هدف از این کتابخونه صرفا انجام یک کار کوچیک و ساده ست و اون هم تبدیل تاریخ های مختلف از/به تقویم شمسی، به طوری که برای جاوا کارها آشنا و طبق کتابخونه ی جدید تایم در جاوا هشت باشه.
متشکرم بابت پیشنهادتون.
