### ISSUE TITLE
Invalid result in PersianDate.fromGregorian() in leaps years (eg: 2025-1403)

### ISSUE THREAD

**Issue by amirsh71** [mfathi91/persian-date-time#7]
Hi,
There is a bug in converting (2025-03-20) to Persian date,
if you convert this date using this method:
```java
PersianDate.fromGregorian(LocalDate.of(2025,3,20))
```
it will return this:
```
1404-01-01
```
which is incorrect and must be:
```
1403-12-30
```

**Comment by mfathi91** [comment]
Hi,

I get the correct results on my machine. So for me `PersianDate.fromGregorian(LocalDate.of(2025,3,20))` returns `1403-12-30` (which is as expected).

Please let me know if the bug is still on your machine, or it was a false positive :wink:

**Comment by amirsh71** [comment]
Yeah you right! this problem has existed in version 4.0.0 and in the latest version (4.2.1) there is no problem. 
thank you.
